Introduction of Metadata filtering & additional minor requested features
aiondemand/aiod-enhanced-interaction pull request #4
Opened 2024-12-30 09:41 UTC by marcel-vesely-kinit

*This is a belated Christmas present by yours truly :)*

# Main changes

This is a rather large PR containing various modifications to the Semantic Search service, namely:
- Incorporation of **Metadata filtering** logic
    - Extraction of metadata from assets (for now we **only support extracting data from HuggingFace datasets**)
    - User query parsing and retrieving filters that could be used to narrow down a list of retrieved assets
        - **Automatic user query parsing utilizing an LLM** (LLM inference is run via Ollama service)
        - **Manually user-defined filters** (filters are defined in the POST request, so an LLM inference is skipped)
- Small changes to API endpoints
    - Expanded the endpoints with **pagination** support and an option to **retrieve entire AIoD assets** directly (not only asset IDs)
    - Added blocking endpoints that wait till the results to a user query are resolved
    - Endpoints also return `num_hits` argument representing the number of assets in the entire MilvusDB that match a specific set of user criteria
- Simplified deployment process
    - Instead of having a ton of docker-compose files that differ from each other in a way they combine services we utilize a Jinja2 templates to build a specific docker-compose with services we wish to include on the fly
- Expanded the garbage collector logic to TinyDB database as well

## Metadata filtering
- TODO

# Potential problems

**Asset pagination** behavior as well as the **hit_count** argument return only an approximate 

- TODO

# Additional planned features
- TODO

2025-01-16 11:52 UTC, andrejridzik requested changes
Reviewing a first batch of modified files (35/49)

2025-01-16 11:52 UTC, andrejridzik commented on api/deploy.sh
> +if [ "$#" -eq 0 ]; then
This is a rather strange way of populating values in jinja template.. Can't we just run a simple `jinja-cli` command directly from this script and potentially add it to requirements/requirements-dev? Running a separate docker container for this seems to me like an overkill, but perhaps I am missing something.

2025-01-16 11:52 UTC, andrejridzik commented on api/scripts/build_compose.py
> +import os
Ideally get rid of this script and replace it with jinja-cli command

2025-01-24 13:17 UTC, marcel-vesely-kinit commented on api/deploy.sh
> +if [ "$#" -eq 0 ]; then
I suppose the idea is to have as few requirements as possible on the machine we wish to use for deployment. In other words, I don't expect said machine to have Python installed for instance, hence the need to run a new Python container that executes a script for building a new Docker/dockercompose.

2025-01-27 10:35 UTC, andrejridzik commented on api/deploy.sh
> +  exit 1
Do we really need t exit here? Similarly above.

2025-01-27 10:35 UTC, andrejridzik commented on api/app/services/threads/search_thread.py
> +                user_query.update_status(QueryStatus.FAILED)
`user_query` might be None on undefined at this point. We can move the initial blocks of code outside of `try-except` block if we don't expect any errors to appear. It would also help the readability of the code.

2025-01-27 10:35 UTC, andrejridzik commented on api/app/services/threads/search_thread.py
> +# TODO perhaps we should move these two function to a different file?
Perhaps to a new service module `service/aiod.py`

2025-01-27 10:37 UTC, andrejridzik commented on api/Dockerfile.build-compose
> +FROM python:3.11
That it can be deleted 😄

2025-01-27 10:39 UTC, andrejridzik commented on api/deploy.sh
> +if [ "$#" -eq 0 ]; then
Lets keep the discussion for a separate PR

2025-01-27 11:11 UTC, andrejridzik requested changes

2025-01-27 11:11 UTC, andrejridzik commented on api/app/services/inference/llm_query_parsing.py
> +            # we compare current LLM output to potentionally previous LLm outputs
```suggestion
            # we compare current LLM output to potentially previous LLM outputs
```

2025-01-27 11:12 UTC, andrejridzik commented
Looks good! Please also move some parts of the PR description to the README file

2025-01-28 14:23 UTC, marcel-vesely-kinit commented on api/app/services/embedding_store.py
> +                    schema.add_field("date_published", DataType.VARCHAR, max_length=22)
Yeah, for now I shall keep it the way it is, since the `populate_milvus.py` file currently doesn't have an access to the other files of the FastAPI application as it is solely used for populating Milvus database in a separate docker container.

But I agree that it needs to be resolved later on

2025-01-28 14:29 UTC, marcel-vesely-kinit commented on api/deploy.sh
> +  exit 1
I believe so. I want these variables to be explicitly defined

2025-01-28 15:35 UTC, marcel-vesely-kinit commented on api/app/services/inference/llm_query_parsing.py
> +class UserQuery_Stage1_OutputSchema(BaseModel):
With these longer class names I tend to use underscore to make it easier to read, it's a Marcel's convention ^^

Ideally I should come up with names that wouldn't be that long in the first place. Since this file may be a subject of change in foreseeable future, I'll simply mark these lovely class names as not appropriate rather than necessarily changing them for now :)

2025-01-29 09:51 UTC, andrejridzik commented on api/README.md
> +### Extracting of filters from user queries
```suggestion
### Metadata extraction from assets

Currently this process applicability is restricted to only a specific subset of assets we can <ins>manually extract metadata</ins> from, from <ins>Huggingface datasets</ins> to be exact. Due to this extraction process being very time demanding, we have opted to perform the metadata extraction manually without any use of LLMs for now. 

Since the datasets as an asset type is the most prevalent asset in the AIoD platform, we have decided to apply metadata filtering on said asset, whilst choosing solely Huggingface datasets that share a common metadata structure as it can be used to retrieve a handful of metadata fields to be stored in Milvus database.

### Filters extraction from user queries
```

2025-01-29 09:51 UTC, andrejridzik commented on api/app/models/query.py
> +    def map_to_response(self, response_model: Type[BaseModel]) -> BaseModel:
I do not fully agree, as this is a standard use case for `TypeVar` to deal with "dynamic type annotation". However, I fine with keeping the current version to no longer postpone the finalization of this PR and ignore the warnings.

2025-01-29 09:52 UTC, andrejridzik approved these changes

2025-01-29 12:00 UTC, merged